import Hero from '@/components/Layout/Hero';
import './globals.css';
import type { Metadata } from 'next';
import mainHero from '@/assets//images/logo-lg.webp';
import { kanit } from '@/assets/fonts/fonts';
import { formattedPhoneNumber } from '@/lib/variables';
import TextWithButtons from '@/components/TextWithButtons';
import CallButton from '@/components/UI/CallButton';
import ContactButton from '@/components/UI/ContactButton';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' data-theme='corporate'>
      <body className={kanit.className}>
        <Hero heroImage={mainHero.src}>
          <TextWithButtons
            text='CALL FOR FREE BOND ADVICE'
            subtext={formattedPhoneNumber}
            buttons={[
              <CallButton key='call-btn' />,
              <ContactButton key='contact-btn' />
            ]}
          />
          {/* <div className='flex flex-col gap-12'>
            <div className='select-none text-shadow'>
              <h1 className='text-6xl text'>CALL FOR FREE BOND ADVICE</h1>
              <h2 className='text-4xl text-primary'>{formattedPhoneNumber}</h2>
            </div>
            <div className='flex gap-6 justify-center'>
              <button className='btn h-16 w-40 text-lg'>CALL NOW</button>
              <button className='btn btn-primary h-16 w-40 text-lg'>CONTACT US</button>
            </div>
          </div> */}
        </Hero>
        {children}
      </body>
    </html>
  );
}
